# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Processes.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Processes(object):
    def setupUi(self, Processes):
        Processes.setObjectName("Processes")
        Processes.resize(628, 425)
        Processes.setMinimumSize(QtCore.QSize(346, 376))
        self.verticalLayout = QtWidgets.QVBoxLayout(Processes)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Table = QtWidgets.QTableWidget(Processes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Table.sizePolicy().hasHeightForWidth())
        self.Table.setSizePolicy(sizePolicy)
        self.Table.setMinimumSize(QtCore.QSize(328, 0))
        self.Table.setObjectName("Table")
        self.Table.setColumnCount(3)
        self.Table.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table.setItem(9, 0, item)
        self.verticalLayout.addWidget(self.Table)
        self.ok = QtWidgets.QDialogButtonBox(Processes)
        self.ok.setOrientation(QtCore.Qt.Horizontal)
        self.ok.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ok.setObjectName("ok")
        self.verticalLayout.addWidget(self.ok)

        self.retranslateUi(Processes)
        self.ok.accepted.connect(Processes.accept)
        self.ok.rejected.connect(Processes.reject)
        QtCore.QMetaObject.connectSlotsByName(Processes)

    def retranslateUi(self, Processes):
        _translate = QtCore.QCoreApplication.translate
        Processes.setWindowTitle(_translate("Processes", "Dialog"))
        item = self.Table.verticalHeaderItem(0)
        item.setText(_translate("Processes", "1"))
        item = self.Table.verticalHeaderItem(1)
        item.setText(_translate("Processes", "2"))
        item = self.Table.verticalHeaderItem(2)
        item.setText(_translate("Processes", "3"))
        item = self.Table.verticalHeaderItem(3)
        item.setText(_translate("Processes", "4"))
        item = self.Table.verticalHeaderItem(4)
        item.setText(_translate("Processes", "5"))
        item = self.Table.verticalHeaderItem(5)
        item.setText(_translate("Processes", "6"))
        item = self.Table.verticalHeaderItem(6)
        item.setText(_translate("Processes", "7"))
        item = self.Table.verticalHeaderItem(7)
        item.setText(_translate("Processes", "8"))
        item = self.Table.verticalHeaderItem(8)
        item.setText(_translate("Processes", "9"))
        item = self.Table.verticalHeaderItem(9)
        item.setText(_translate("Processes", "10"))
        item = self.Table.horizontalHeaderItem(0)
        item.setText(_translate("Processes", "Burst Time"))
        item = self.Table.horizontalHeaderItem(1)
        item.setText(_translate("Processes", "Processes"))
        item = self.Table.horizontalHeaderItem(2)
        item.setText(_translate("Processes", "Arrival Time"))
        __sortingEnabled = self.Table.isSortingEnabled()
        self.Table.setSortingEnabled(False)
        self.Table.setSortingEnabled(__sortingEnabled)


